baseURL = 'https://tobias-piotr.github.io'
languageCode = 'en-us'
title = 'tobiwan.dev'
theme = "blowfish"

[taxonomies]
  post = "articles"	
  tag = "tags"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
